[global]
width = 512
height = 512
output_directory = "./dist/"

[mandelbrot]
xmin = -2
ymin = -2
xmax = +2
ymax = +2
iterations = 200
contrast = 15
output_file = "mandelbrot.png"

[julia]
xmin = -2
ymin = -2
xmax = +2
ymax = +2
c_real = -0.8
c_imag = 0.156
iterations = 200
contrast = 15
output_file = "julia.png"

[tricorn]
xmin = -2
ymin = -2
xmax = +2
ymax = +2
c_real = -0.8
c_imag = 0.156
iterations = 200
contrast = 15
output_file = "tricorn.png"

[burning_ship]
xmin = -1.8
xmax = -1.7
ymin = -0.1
ymax = 0.02
iterations = 20
contrast = 1
output_file = "burning_ship.png"
